apiVersion: v2
description: A Helm chart cert-manager ACME Webhook for INWX
name: cert-manager-webhook-inwx
version: 0.5.0
appVersion: 0.5.0
maintainers:
  - name: Stephan MÃ¼ller
    url: https://gitlab.com/smueller18/cert-manager-webhook-inwx
